-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 14:30:30 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Appointments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Appointments` (
  `id Appointments` INT NOT NULL,
  `id Doctor` VARCHAR(45) NOT NULL,
  `id schedule` VARCHAR(45) NULL,
  `Recording status` VARCHAR(45) NULL,
  PRIMARY KEY (`id Appointments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Patients` (
  `idPatients` INT NULL,
  `FIO` VARCHAR(45) NULL,
  `Дата рождения` VARCHAR(45) NULL,
  `Pol` VARCHAR(45) NULL,
  `№Polis` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Appointments_id Appointments` INT NOT NULL,
  PRIMARY KEY (`idPatients`, `Appointments_id Appointments`),
  INDEX `fk_Patients_Appointments1_idx` (`Appointments_id Appointments` ASC) VISIBLE,
  CONSTRAINT `fk_Patients_Appointments1`
    FOREIGN KEY (`Appointments_id Appointments`)
    REFERENCES `mydb`.`Appointments` (`id Appointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Schedule` (
  `idSchedule` INT NOT NULL,
  `id Doctor` VARCHAR(45) NULL,
  `Data` VARCHAR(45) NULL,
  `Star Time` VARCHAR(45) NULL,
  `End Time` VARCHAR(45) NULL,
  `Appointments_id Appointments` INT NOT NULL,
  PRIMARY KEY (`idSchedule`, `Appointments_id Appointments`),
  INDEX `fk_Schedule_Appointments1_idx` (`Appointments_id Appointments` ASC) VISIBLE,
  CONSTRAINT `fk_Schedule_Appointments1`
    FOREIGN KEY (`Appointments_id Appointments`)
    REFERENCES `mydb`.`Appointments` (`id Appointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Doctors` (
  `idDoctors` INT NOT NULL,
  `FIO` VARCHAR(45) NULL,
  `Specialization` VARCHAR(45) NULL,
  `Office` VARCHAR(45) NULL,
  `Schedule_idSchedule` INT NOT NULL,
  PRIMARY KEY (`idDoctors`),
  INDEX `fk_Doctors_Schedule_idx` (`Schedule_idSchedule` ASC) VISIBLE,
  CONSTRAINT `fk_Doctors_Schedule`
    FOREIGN KEY (`Schedule_idSchedule`)
    REFERENCES `mydb`.`Schedule` (`idSchedule`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnoses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnoses` (
  `idDiagnoses` INT NOT NULL,
  `Code Diagnose` VARCHAR(45) NULL,
  `Name Diagnose` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  PRIMARY KEY (`idDiagnoses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Visits` (
  `idVisits` INT NOT NULL,
  `id Records` VARCHAR(45) NULL,
  `id Diagnose` VARCHAR(45) NULL,
  `Date Of Admission` VARCHAR(45) NULL,
  `Appointments_id Appointments` INT NOT NULL,
  PRIMARY KEY (`idVisits`, `Appointments_id Appointments`),
  INDEX `fk_Visits_Appointments1_idx` (`Appointments_id Appointments` ASC) VISIBLE,
  CONSTRAINT `fk_Visits_Appointments1`
    FOREIGN KEY (`Appointments_id Appointments`)
    REFERENCES `mydb`.`Appointments` (`id Appointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Diagnoses_has_Visits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Diagnoses_has_Visits` (
  `Diagnoses_idDiagnoses` INT NOT NULL,
  `Visits_idVisits` INT NOT NULL,
  `Visits_Appointments_id Appointments` INT NOT NULL,
  PRIMARY KEY (`Diagnoses_idDiagnoses`, `Visits_idVisits`, `Visits_Appointments_id Appointments`),
  INDEX `fk_Diagnoses_has_Visits_Visits1_idx` (`Visits_idVisits` ASC, `Visits_Appointments_id Appointments` ASC) VISIBLE,
  INDEX `fk_Diagnoses_has_Visits_Diagnoses1_idx` (`Diagnoses_idDiagnoses` ASC) VISIBLE,
  CONSTRAINT `fk_Diagnoses_has_Visits_Diagnoses1`
    FOREIGN KEY (`Diagnoses_idDiagnoses`)
    REFERENCES `mydb`.`Diagnoses` (`idDiagnoses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Diagnoses_has_Visits_Visits1`
    FOREIGN KEY (`Visits_idVisits` , `Visits_Appointments_id Appointments`)
    REFERENCES `mydb`.`Visits` (`idVisits` , `Appointments_id Appointments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
